In [1]:
import re
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [4]:
url = "https://www.transfermarkt.com.br/premier-league/startseite/wettbewerb/GB1/plus/?saison_id=2025"

headers = {
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:150.0) Gecko/20100101 Firefox/150.0"
}

response = requests.get(url, headers=headers)

response.status_code

200

In [5]:
soup = BeautifulSoup(response.content, "html.parser")

In [8]:
teamSoup = soup.find_all('td', {'class':'rechts'})

display(teamSoup)

[<td class="rechts">€ 23.82 mi.</td>,
 <td class="rechts">€ 12.58 Bi.</td>,
 <td class="rechts">€ 48.69 mi.</td>,
 <td class="rechts"><a href="/manchester-city-fc/kader/verein/281/saison_id/2025" title="Manchester City FC">€ 1.31 Bi.</a></td>,
 <td class="rechts">€ 49.16 mi.</td>,
 <td class="rechts"><a href="/fc-arsenal/kader/verein/11/saison_id/2025" title="FC Arsenal">€ 1.23 Bi.</a></td>,
 <td class="rechts">€ 37.55 mi.</td>,
 <td class="rechts"><a href="/chelsea-fc/kader/verein/631/saison_id/2025" title="Chelsea FC">€ 1.16 Bi.</a></td>,
 <td class="rechts">€ 36.59 mi.</td>,
 <td class="rechts"><a href="/fc-liverpool/kader/verein/31/saison_id/2025" title="FC Liverpool">€ 1.02 Bi.</a></td>,
 <td class="rechts">€ 28.66 mi.</td>,
 <td class="rechts"><a href="/tottenham-hotspur/kader/verein/148/saison_id/2025" title="Tottenham Hotspur">€ 802.50 mi.</a></td>,
 <td class="rechts">€ 31.13 mi.</td>,
 <td class="rechts"><a href="/manchester-united-fc/kader/verein/985/saison_id/2025" title="Manchester United FC">€ 747.15 mi.</a></td>,
 <td class="rechts">€ 27.24 mi.</td>,
 <td class="rechts"><a href="/newcastle-united/kader/verein/762/saison_id/2025" title="Newcastle United">€ 708.25 mi.</a></td>,
 <td class="rechts">€ 19.59 mi.</td>,
 <td class="rechts"><a href="/nottingham-forest/kader/verein/703/saison_id/2025" title="Nottingham Forest">€ 568.00 mi.</a></td>,
 <td class="rechts">€ 21.90 mi.</td>,
 <td class="rechts"><a href="/aston-villa-fc/kader/verein/405/saison_id/2025" title="Aston Villa FC">€ 547.50 mi.</a></td>,
 <td class="rechts">€ 19.33 mi.</td>,
 <td class="rechts"><a href="/crystal-palace-fc/kader/verein/873/saison_id/2025" title="Crystal Palace FC">€ 541.30 mi.</a></td>,
 <td class="rechts">€ 19.50 mi.</td>,
 <td class="rechts"><a href="/afc-bournemouth/kader/verein/989/saison_id/2025" title="AFC Bournemouth">€ 507.10 mi.</a></td>,
 <td class="rechts">€ 19.00 mi.</td>,
 <td class="rechts"><a href="/brighton-amp-hove-albion/kader/verein/1237/saison_id/2025" title="Brighton &amp; Hove Albion">€ 494.00 mi.</a></td>,
 <td class="rechts">€ 18.09 mi.</td>,
 <td class="rechts"><a href="/brentford-fc/kader/verein/1148/saison_id/2025" title="Brentford FC">€ 470.40 mi.</a></td>,
 <td class="rechts">€ 18.02 mi.</td>,
 <td class="rechts"><a href="/fc-everton/kader/verein/29/saison_id/2025" title="FC Everton">€ 450.45 mi.</a></td>,
 <td class="rechts">€ 16.12 mi.</td>,
 <td class="rechts"><a href="/fc-fulham/kader/verein/931/saison_id/2025" title="FC Fulham">€ 386.95 mi.</a></td>,
 <td class="rechts">€ 13.64 mi.</td>,
 <td class="rechts"><a href="/afc-sunderland/kader/verein/289/saison_id/2025" title="AFC Sunderland">€ 381.95 mi.</a></td>,
 <td class="rechts">€ 15.12 mi.</td>,
 <td class="rechts"><a href="/west-ham-united/kader/verein/379/saison_id/2025" title="West Ham United">€ 362.95 mi.</a></td>,
 <td class="rechts">€ 13.31 mi.</td>,
 <td class="rechts"><a href="/leeds-united-fc/kader/verein/399/saison_id/2025" title="Leeds United FC">€ 346.03 mi.</a></td>,
 <td class="rechts">€ 12.05 mi.</td>,
 <td class="rechts"><a href="/wolverhampton-wanderers/kader/verein/543/saison_id/2025" title="Wolverhampton Wanderers">€ 277.10 mi.</a></td>,
 <td class="rechts">€ 8.71 mi.</td>,
 <td class="rechts"><a href="/fc-burnley/kader/verein/1132/saison_id/2025" title="FC Burnley">€ 252.65 mi.</a></td>,
 <td class="rechts hauptlink" style="background-color: #afd179">1 <span class="icons_sprite grey-block-ten" title="Última rodada 1.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #c3dc9a">2 <span class="icons_sprite grey-block-ten" title="Última rodada 2.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #c3dc9a">3 <span class="icons_sprite grey-block-ten" title="Última rodada 3.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #c3dc9a">4 <span class="icons_sprite grey-block-ten" title="Última rodada 4.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #c3dc9a">5 <span class="icons_sprite grey-block-ten" title="Última rodada 5.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #bdd9ef">6 <span class="icons_sprite grey-block-ten" title="Última rodada 6.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #bdd9ef">7 <span class="icons_sprite green-arrow-ten" title="Última rodada 10.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #fee492">8 <span class="icons_sprite red-arrow-ten" title="Última rodada 7.posição"> </span></td>,
 <td class="rechts hauptlink">9 <span class="icons_sprite grey-block-ten" title="Última rodada 9.posição"> </span></td>,
 <td class="rechts hauptlink">10 <span class="icons_sprite red-arrow-ten" title="Última rodada 8.posição"> </span></td>,
 <td class="rechts hauptlink">11 <span class="icons_sprite green-arrow-ten" title="Última rodada 13.posição"> </span></td>,
 <td class="rechts hauptlink">12 <span class="icons_sprite red-arrow-ten" title="Última rodada 11.posição"> </span></td>,
 <td class="rechts hauptlink">13 <span class="icons_sprite red-arrow-ten" title="Última rodada 12.posição"> </span></td>,
 <td class="rechts hauptlink">14 <span class="icons_sprite grey-block-ten" title="Última rodada 14.posição"> </span></td>,
 <td class="rechts hauptlink">15 <span class="icons_sprite grey-block-ten" title="Última rodada 15.posição"> </span></td>,
 <td class="rechts hauptlink">16 <span class="icons_sprite grey-block-ten" title="Última rodada 16.posição"> </span></td>,
 <td class="rechts hauptlink">17 <span class="icons_sprite grey-block-ten" title="Última rodada 17.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #f8a7a3">18 <span class="icons_sprite grey-block-ten" title="Última rodada 18.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #f8a7a3">19 <span class="icons_sprite grey-block-ten" title="Última rodada 19.posição"> </span></td>,
 <td class="rechts hauptlink" style="background-color: #f8a7a3">20 <span class="icons_sprite grey-block-ten" title="Última rodada 20.posição"> </span></td>]

In [23]:
display(teamSoup[3])

teamSoup[3]

display(teamSoup[3].string)

if 'href' in str(teamSoup[3]):
    print('yo')

'€ 1.31 Bi.'

yo

In [32]:
team_value = []

for i, row in enumerate(teamSoup):
    temp = []
    if "href" in str(row):
        temp.append(re.search('title="(.*)">€', str(row)).group(1))
        temp.append(row.string)
        team_value.append(temp)
    else: continue

df = pd.DataFrame(team_value)
df.columns = ['Clube','Value']
display(df)

                         Clube         Value
0           Manchester City FC    € 1.31 Bi.
1                   FC Arsenal    € 1.23 Bi.
2                   Chelsea FC    € 1.16 Bi.
3                 FC Liverpool    € 1.02 Bi.
4            Tottenham Hotspur  € 802.50 mi.
5         Manchester United FC  € 747.15 mi.
6             Newcastle United  € 708.25 mi.
7            Nottingham Forest  € 568.00 mi.
8               Aston Villa FC  € 547.50 mi.
9            Crystal Palace FC  € 541.30 mi.
10             AFC Bournemouth  € 507.10 mi.
11  Brighton &amp; Hove Albion  € 494.00 mi.
12                Brentford FC  € 470.40 mi.
13                  FC Everton  € 450.45 mi.
14                   FC Fulham  € 386.95 mi.
15              AFC Sunderland  € 381.95 mi.
16             West Ham United  € 362.95 mi.
17             Leeds United FC  € 346.03 mi.
18     Wolverhampton Wanderers  € 277.10 mi.
19                  FC Burnley  € 252.65 mi.

In [44]:
estrangeiro = soup.find_all('td', {'class':'zentriert'})
del estrangeiro[:3]
display(estrangeiro)

[<td class="zentriert no-border-rechts"><a href="/manchester-city/startseite/verein/281/saison_id/2025" title="Manchester City FC"><img alt="Manchester City FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/281.png?lm=1467356331" title="Manchester City FC"/></a></td>,
 <td class="zentriert"><a href="/manchester-city-fc/kader/verein/281/saison_id/2025" title="Manchester City FC">27</a></td>,
 <td class="zentriert">26.2</td>,
 <td class="zentriert">19</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-arsenal/startseite/verein/11/saison_id/2025" title="FC Arsenal"><img alt="FC Arsenal" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/11.png?lm=1489787850" title="FC Arsenal"/></a></td>,
 <td class="zentriert"><a href="/fc-arsenal/kader/verein/11/saison_id/2025" title="FC Arsenal">25</a></td>,
 <td class="zentriert">26.3</td>,
 <td class="zentriert">17</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-chelsea/startseite/verein/631/saison_id/2025" title="Chelsea FC"><img alt="Chelsea FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/631.png?lm=1682435911" title="Chelsea FC"/></a></td>,
 <td class="zentriert"><a href="/chelsea-fc/kader/verein/631/saison_id/2025" title="Chelsea FC">31</a></td>,
 <td class="zentriert">23.7</td>,
 <td class="zentriert">21</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-liverpool/startseite/verein/31/saison_id/2025" title="FC Liverpool"><img alt="FC Liverpool" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/31.png?lm=1727873452" title="FC Liverpool"/></a></td>,
 <td class="zentriert"><a href="/fc-liverpool/kader/verein/31/saison_id/2025" title="FC Liverpool">28</a></td>,
 <td class="zentriert">26.1</td>,
 <td class="zentriert">21</td>,
 <td class="zentriert no-border-rechts"><a href="/tottenham-hotspur/startseite/verein/148/saison_id/2025" title="Tottenham Hotspur"><img alt="Tottenham Hotspur" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/148.png?lm=1732011953" title="Tottenham Hotspur"/></a></td>,
 <td class="zentriert"><a href="/tottenham-hotspur/kader/verein/148/saison_id/2025" title="Tottenham Hotspur ">28</a></td>,
 <td class="zentriert">26.0</td>,
 <td class="zentriert">22</td>,
 <td class="zentriert no-border-rechts"><a href="/manchester-united/startseite/verein/985/saison_id/2025" title="Manchester United FC"><img alt="Manchester United FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/985.png?lm=1457975903" title="Manchester United FC"/></a></td>,
 <td class="zentriert"><a href="/manchester-united-fc/kader/verein/985/saison_id/2025" title="Manchester United FC">24</a></td>,
 <td class="zentriert">26.7</td>,
 <td class="zentriert">18</td>,
 <td class="zentriert no-border-rechts"><a href="/newcastle-united/startseite/verein/762/saison_id/2025" title="Newcastle United"><img alt="Newcastle United" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/762.png?lm=1472921161" title="Newcastle United"/></a></td>,
 <td class="zentriert"><a href="/newcastle-united/kader/verein/762/saison_id/2025" title="Newcastle United">26</a></td>,
 <td class="zentriert">28.2</td>,
 <td class="zentriert">12</td>,
 <td class="zentriert no-border-rechts"><a href="/nottingham-forest/startseite/verein/703/saison_id/2025" title="Nottingham Forest"><img alt="Nottingham Forest" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/703.png?lm=1598890289" title="Nottingham Forest"/></a></td>,
 <td class="zentriert"><a href="/nottingham-forest/kader/verein/703/saison_id/2025" title="Nottingham Forest">29</a></td>,
 <td class="zentriert">26.7</td>,
 <td class="zentriert">22</td>,
 <td class="zentriert no-border-rechts"><a href="/aston-villa/startseite/verein/405/saison_id/2025" title="Aston Villa FC"><img alt="Aston Villa FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/405.png?lm=1717155982" title="Aston Villa FC"/></a></td>,
 <td class="zentriert"><a href="/aston-villa-fc/kader/verein/405/saison_id/2025" title="Aston Villa FC">25</a></td>,
 <td class="zentriert">28.3</td>,
 <td class="zentriert">17</td>,
 <td class="zentriert no-border-rechts"><a href="/crystal-palace/startseite/verein/873/saison_id/2025" title="Crystal Palace FC"><img alt="Crystal Palace FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/873.png?lm=1457723287" title="Crystal Palace FC"/></a></td>,
 <td class="zentriert"><a href="/crystal-palace-fc/kader/verein/873/saison_id/2025" title="Crystal Palace FC">28</a></td>,
 <td class="zentriert">26.5</td>,
 <td class="zentriert">19</td>,
 <td class="zentriert no-border-rechts"><a href="/afc-bournemouth/startseite/verein/989/saison_id/2025" title="AFC Bournemouth"><img alt="AFC Bournemouth" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/989.png?lm=1457991811" title="AFC Bournemouth"/></a></td>,
 <td class="zentriert"><a href="/afc-bournemouth/kader/verein/989/saison_id/2025" title="AFC Bournemouth">26</a></td>,
 <td class="zentriert">25.6</td>,
 <td class="zentriert">20</td>,
 <td class="zentriert no-border-rechts"><a href="/brighton-amp-hove-albion/startseite/verein/1237/saison_id/2025" title="Brighton &amp; Hove Albion"><img alt="Brighton &amp; Hove Albion" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/1237.png?lm=1492718902" title="Brighton &amp; Hove Albion"/></a></td>,
 <td class="zentriert"><a href="/brighton-amp-hove-albion/kader/verein/1237/saison_id/2025" title="Brighton &amp; Hove Albion">26</a></td>,
 <td class="zentriert">27.7</td>,
 <td class="zentriert">19</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-brentford/startseite/verein/1148/saison_id/2025" title="Brentford FC"><img alt="Brentford FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/1148.png?lm=1625150543" title="Brentford FC"/></a></td>,
 <td class="zentriert"><a href="/brentford-fc/kader/verein/1148/saison_id/2025" title="Brentford FC">26</a></td>,
 <td class="zentriert">25.5</td>,
 <td class="zentriert">20</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-everton/startseite/verein/29/saison_id/2025" title="FC Everton"><img alt="FC Everton" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/29.png?lm=1445949846" title="FC Everton"/></a></td>,
 <td class="zentriert"><a href="/fc-everton/kader/verein/29/saison_id/2025" title="FC Everton">25</a></td>,
 <td class="zentriert">26.8</td>,
 <td class="zentriert">13</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-fulham/startseite/verein/931/saison_id/2025" title="FC Fulham"><img alt="FC Fulham" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/931.png?lm=1556831687" title="FC Fulham"/></a></td>,
 <td class="zentriert"><a href="/fc-fulham/kader/verein/931/saison_id/2025" title="FC Fulham">24</a></td>,
 <td class="zentriert">28.3</td>,
 <td class="zentriert">20</td>,
 <td class="zentriert no-border-rechts"><a href="/afc-sunderland/startseite/verein/289/saison_id/2025" title="AFC Sunderland"><img alt="AFC Sunderland" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/289.png?lm=1485645633" title="AFC Sunderland"/></a></td>,
 <td class="zentriert"><a href="/afc-sunderland/kader/verein/289/saison_id/2025" title="AFC Sunderland">28</a></td>,
 <td class="zentriert">25.2</td>,
 <td class="zentriert">23</td>,
 <td class="zentriert no-border-rechts"><a href="/west-ham-united/startseite/verein/379/saison_id/2025" title="West Ham United"><img alt="West Ham United" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/379.png?lm=1464675260" title="West Ham United"/></a></td>,
 <td class="zentriert"><a href="/west-ham-united/kader/verein/379/saison_id/2025" title="West Ham United">24</a></td>,
 <td class="zentriert">26.7</td>,
 <td class="zentriert">17</td>,
 <td class="zentriert no-border-rechts"><a href="/leeds-united/startseite/verein/399/saison_id/2025" title="Leeds United FC"><img alt="Leeds United FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/399.png?lm=1645652224" title="Leeds United FC"/></a></td>,
 <td class="zentriert"><a href="/leeds-united-fc/kader/verein/399/saison_id/2025" title="Leeds United FC ">26</a></td>,
 <td class="zentriert">27.3</td>,
 <td class="zentriert">20</td>,
 <td class="zentriert no-border-rechts"><a href="/wolverhampton-wanderers/startseite/verein/543/saison_id/2025" title="Wolverhampton Wanderers"><img alt="Wolverhampton Wanderers" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/543.png?lm=1467496784" title="Wolverhampton Wanderers"/></a></td>,
 <td class="zentriert"><a href="/wolverhampton-wanderers/kader/verein/543/saison_id/2025" title="Wolverhampton Wanderers">23</a></td>,
 <td class="zentriert">26.4</td>,
 <td class="zentriert">19</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-burnley/startseite/verein/1132/saison_id/2025" title="FC Burnley"><img alt="FC Burnley" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/1132.png?lm=1686818840" title="FC Burnley"/></a></td>,
 <td class="zentriert"><a href="/fc-burnley/kader/verein/1132/saison_id/2025" title="FC Burnley">29</a></td>,
 <td class="zentriert">27.8</td>,
 <td class="zentriert">21</td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626159"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626165"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626161"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626163"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626164"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626167"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626166"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626158"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626160"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="37" data-match="4626162"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626168"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626169"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626170"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626171"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626172"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626173"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626174"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626175"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626176"></span> </td>,
 <td class="zentriert quotenzelle hide-for-small" onclick="tmEvent('werbung','click','wettbewerbsset');">
 <span class="oddsServe" data-competition="GB1" data-gameday="38" data-match="4626177"></span> </td>,
 <td class="zentriert no-border-rechts"><a href="/fc-arsenal/spielplan/verein/11/saison_id/2025" title="FC Arsenal"><img alt="FC Arsenal" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/11.png?lm=1489787850" title="FC Arsenal"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">44</td>,
 <td class="zentriert">85</td>,
 <td class="zentriert no-border-rechts"><a href="/manchester-city/spielplan/verein/281/saison_id/2025" title="Manchester City FC"><img alt="Manchester City FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/281.png?lm=1467356331" title="Manchester City FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">42</td>,
 <td class="zentriert">78</td>,
 <td class="zentriert no-border-rechts"><a href="/manchester-united/spielplan/verein/985/saison_id/2025" title="Manchester United FC"><img alt="Manchester United FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/985.png?lm=1457975903" title="Manchester United FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">19</td>,
 <td class="zentriert">71</td>,
 <td class="zentriert no-border-rechts"><a href="/aston-villa/spielplan/verein/405/saison_id/2025" title="Aston Villa FC"><img alt="Aston Villa FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/405.png?lm=1717155982" title="Aston Villa FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">7</td>,
 <td class="zentriert">65</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-liverpool/spielplan/verein/31/saison_id/2025" title="FC Liverpool"><img alt="FC Liverpool" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/31.png?lm=1727873452" title="FC Liverpool"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">10</td>,
 <td class="zentriert">60</td>,
 <td class="zentriert no-border-rechts"><a href="/afc-bournemouth/spielplan/verein/989/saison_id/2025" title="AFC Bournemouth"><img alt="AFC Bournemouth" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/989.png?lm=1457991811" title="AFC Bournemouth"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">4</td>,
 <td class="zentriert">57</td>,
 <td class="zentriert no-border-rechts"><a href="/afc-sunderland/spielplan/verein/289/saison_id/2025" title="AFC Sunderland"><img alt="AFC Sunderland" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/289.png?lm=1485645633" title="AFC Sunderland"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-6</td>,
 <td class="zentriert">54</td>,
 <td class="zentriert no-border-rechts"><a href="/brighton-amp-hove-albion/spielplan/verein/1237/saison_id/2025" title="Brighton &amp; Hove Albion"><img alt="Brighton &amp; Hove Albion" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/1237.png?lm=1492718902" title="Brighton &amp; Hove Albion"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">6</td>,
 <td class="zentriert">53</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-brentford/spielplan/verein/1148/saison_id/2025" title="Brentford FC"><img alt="Brentford FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/1148.png?lm=1625150543" title="Brentford FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">3</td>,
 <td class="zentriert">53</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-chelsea/spielplan/verein/631/saison_id/2025" title="Chelsea FC"><img alt="Chelsea FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/631.png?lm=1682435911" title="Chelsea FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">6</td>,
 <td class="zentriert">52</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-fulham/spielplan/verein/931/saison_id/2025" title="FC Fulham"><img alt="FC Fulham" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/931.png?lm=1556831687" title="FC Fulham"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-4</td>,
 <td class="zentriert">52</td>,
 <td class="zentriert no-border-rechts"><a href="/newcastle-united/spielplan/verein/762/saison_id/2025" title="Newcastle United"><img alt="Newcastle United" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/762.png?lm=1472921161" title="Newcastle United"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-2</td>,
 <td class="zentriert">49</td>,
 <td class="zentriert no-border-rechts"><a href="/fc-everton/spielplan/verein/29/saison_id/2025" title="FC Everton"><img alt="FC Everton" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/29.png?lm=1445949846" title="FC Everton"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-3</td>,
 <td class="zentriert">49</td>,
 <td class="zentriert no-border-rechts"><a href="/leeds-united/spielplan/verein/399/saison_id/2025" title="Leeds United FC "><img alt="Leeds United FC " class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/399.png?lm=1645652224" title="Leeds United FC "/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-7</td>,
 <td class="zentriert">47</td>,
 <td class="zentriert no-border-rechts"><a href="/crystal-palace/spielplan/verein/873/saison_id/2025" title="Crystal Palace FC"><img alt="Crystal Palace FC" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/873.png?lm=1457723287" title="Crystal Palace FC"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-10</td>,
 <td class="zentriert">45</td>,
 <td class="zentriert no-border-rechts"><a href="/nottingham-forest/spielplan/verein/703/saison_id/2025" title="Nottingham Forest"><img alt="Nottingham Forest" class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/703.png?lm=1598890289" title="Nottingham Forest"/></a></td>,
 <td class="zentriert">38</td>,
 <td class="zentriert">-3</td>,
 <td class="zentriert">44</td>,
 <td class="zentriert no-border-rechts"><a href="/tottenham-hotspur/spielplan/verein/148/saison_id/2025" title="Tottenham Hotspur "><img alt="Tottenham Hotspur " class="tiny_wappen" src="https://tmssl.akamaized.net//images/wappen/tiny/148.png?lm=1732011953" title="Tottenham Hotspur "/></a></td>,
 <td class="zentriert">38</td>,

In [57]:
#title="(.*)"><img

clock = 0
list_plantel = []
temp1=[]
for row in estrangeiro:
    if clock == 0:
        temp1.append(re.search('title="(.*)"><img', str(row)).group(1))
    if clock == 1:
        temp1.append(row.string)
    if clock == 3:
        temp1.append(row.string)
        clock = -1
        list_plantel.append(temp1)
        temp1=[]
    clock+=1
    if len(list_plantel) == 20:
        break

df_plantel = pd.DataFrame(list_plantel)
df_plantel.columns = ['Clube', 'Plantel', 'Estrangeiros']
display(df_plantel)

                         Clube Plantel Estrangeiros
0           Manchester City FC      27           19
1                   FC Arsenal      25           17
2                   Chelsea FC      31           21
3                 FC Liverpool      28           21
4            Tottenham Hotspur      28           22
5         Manchester United FC      24           18
6             Newcastle United      26           12
7            Nottingham Forest      29           22
8               Aston Villa FC      25           17
9            Crystal Palace FC      28           19
10             AFC Bournemouth      26           20
11  Brighton &amp; Hove Albion      26           19
12                Brentford FC      26           20
13                  FC Everton      25           13
14                   FC Fulham      24           20
15              AFC Sunderland      28           23
16             West Ham United      24           17
17             Leeds United FC      26           20
18     Wolverhampton Wanderers      23           19
19                  FC Burnley      29           21