**Countries to fix**
Bosnia-Herzegovina;
Congo;
Cote d'Ivoire;
Curacao;
Czech Republic;
Korea, South;
St. Kitts & Nevis;
The Gambia;
Türkiye

**Right Countries**
Bosnia and Herzegovina;
Republic of the Congo;
Côte d'Ivoire;
Curaçao;
Czechia;
South Korea;
Saint Kitts and Nevis;
Gambia;
Turkey

**Teams to fix**
Brighton & Hove Albion
Oldham Athletic

**Create**
team_id
country_id
season dimension
premier logo if team_name == for 2 clubs

# Data Modeling

In [4]:
import pandas as pd
import numpy as np

In [5]:
to_be_fixed = pd.read_csv(r'..\data-csv\premier-top-scorers.csv')

u = pd.unique(to_be_fixed['country']).copy()


display(np.sort(u))

array(['Albania', 'Algeria', 'Angola', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Benin', 'Bermuda', 'Bosnia-Herzegovina',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cameroon',
       'Canada', 'Chile', 'China', 'Colombia', 'Congo', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Czech Republic',
       'DR Congo', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt',
       'England', 'Equatorial Guinea', 'Estonia', 'Finland', 'France',
       'French Guiana', 'Gabon', 'Georgia', 'Germany', 'Ghana',
       'Gibraltar', 'Greece', 'Grenada', 'Guadeloupe', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'Iran', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Kenya', 'Korea, South', 'Kosovo', 'Latvia',
       'Liberia', 'Mali', 'Malta', 'Martinique', 'Mauritania', 'Mexico',
       'Montenegro', 'Montserrat', 'Morocco', 'Netherlands',
       'New Zealand', 'Nigeria', 'North Macedonia', 'Northern Ireland',
       'Norway', 'Paraguay', 'Peru', 'Poland', 'Portugal', 'Romania',
       'Russia', 'Scotland', 'Senegal', 'Serbia', 'Sierra Leone',
       'Slovakia', 'Slovenia', 'South Africa', 'Spain',
       'St. Kitts & Nevis', 'Sweden', 'Switzerland', 'Tanzania',
       'The Gambia', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Türkiye',
       'Ukraine', 'United States', 'Uruguay', 'Venezuela', 'Wales',
       'Zambia', 'Zimbabwe'], dtype=object)

In [17]:
display(to_be_fixed)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1

In [6]:
flags = pd.read_csv(r'..\data-csv\country-flags.csv')

display(flags)

               country       area  population abr                     svg_url
0          Afghanistan   652230.0  32225560.0  af  https://flagcdn.com/af.svg
1        Åland Islands     1580.0     29789.0  ax  https://flagcdn.com/ax.svg
2              Albania    28748.0   2862427.0  al  https://flagcdn.com/al.svg
3              Algeria  2381740.0  43000000.0  dz  https://flagcdn.com/dz.svg
4       American Samoa      199.0     56700.0  as  https://flagcdn.com/as.svg
..                 ...        ...         ...  ..                         ...
249  Wallis and Futuna      142.0     11700.0  wf  https://flagcdn.com/wf.svg
250     Western Sahara   266000.0    582463.0  eh  https://flagcdn.com/eh.svg
251              Yemen   527968.0  29161922.0  ye  https://flagcdn.com/ye.svg
252             Zambia   752612.0  17381168.0  zm  https://flagcdn.com/zm.svg
253           Zimbabwe   390757.0  15159624.0  zw  https://flagcdn.com/zw.svg

[254 rows x 5 columns]

In [ ]:
right = "Bosnia and Herzegovina;Republic of the Congo;Côte d'Ivoire;Curaçao;Czechia;South Korea;Saint Kitts and Nevis;Gambia;Turkey"
wrong = "Bosnia-Herzegovina;Congo;Cote d'Ivoire;Curacao;Czech Republic;Korea, South;St. Kitts & Nevis;The Gambia;Türkiye"

right_list = right.split(';')
wrong_list = wrong.split(';')

display(right_list)
display(wrong_list)

['Bosnia and Herzegovina',
 'Republic of the Congo',
 "Côte d'Ivoire",
 'Curaçao',
 'Czechia',
 'South Korea',
 'Saint Kitts and Nevis',
 'Gambia',
 'Turkey']

['Bosnia-Herzegovina',
 'Congo',
 "Cote d'Ivoire",
 'Curacao',
 'Czech Republic',
 'Korea, South',
 'St. Kitts & Nevis',
 'The Gambia',
 'Türkiye']

In [ ]:
count = 0
for i, row in enumerate(to_be_fixed['country']):
    if row in wrong_list:
        to_be_fixed.replace()
        count += 1
print(i)
print(count)

8924
237

In [16]:
new_df = to_be_fixed.copy()
for i, row in enumerate(wrong_list):
    new_df.replace(wrong_list[i],right_list[i],inplace=True)

display(new_df)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1