**Countries to fix**
- Bosnia-Herzegovina;
- Congo;
- Cote d'Ivoire;
- Curacao;
- Czech Republic;
- Korea, South;
- St. Kitts & Nevis;
- The Gambia;
- Türkiye

**Right Countries**
- Bosnia and Herzegovina;
- Republic of the Congo;
- Côte d'Ivoire;
- Curaçao;
- Czechia;
- South Korea;
- Saint Kitts and Nevis;
- Gambia;
- Turkey

**Teams to fix**
- Brighton & Hove Albion
- Oldham Athletic

**Create**
- team_id
- country_id
- season dimension
- premier logo if team_name == for 2 clubs

# Data Modeling

In [5]:
import pandas as pd
import numpy as np

In [6]:
to_be_fixed = pd.read_csv(r'..\data-csv\premier-top-scorers.csv')

display(to_be_fixed)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1

In [7]:
right = "Bosnia and Herzegovina;Republic of the Congo;Côte d'Ivoire;Curaçao;Czechia;South Korea;Saint Kitts and Nevis;Gambia;Turkey"
wrong = "Bosnia-Herzegovina;Congo;Cote d'Ivoire;Curacao;Czech Republic;Korea, South;St. Kitts & Nevis;The Gambia;Türkiye"

right_list = right.split(';')
wrong_list = wrong.split(';')

new_df = to_be_fixed.copy()
for i, row in enumerate(wrong_list):
    new_df.replace(wrong_list[i],right_list[i],inplace=True)

display(new_df)

,season_id,pos,country,age,player_name,team,matches,goals
0,GB1-1992,1,England,27,Teddy Sheringham,for 2 clubs,41,22
1,GB1-1992,2,England,26,Les Ferdinand,Queens Park Rangers,37,20
2,GB1-1992,3,England,24,Dean Holdsworth,Wimbledon FC (- 2004),36,19
3,GB1-1992,4,England,31,Micky Quinn,Coventry City,26,17
4,GB1-1992,5,England,25,David White,Manchester City,42,16
...,...,...,...,...,...,...,...,...
8920,GB1-2025,276,Denmark,25,Matt O'Riley,Brighton & Hove Albion,6,1
8921,GB1-2025,277,Portugal,23,Fábio Carvalho,Brentford FC,6,1
8922,GB1-2025,278,Italy,25,Lorenzo Lucca,Nottingham Forest,4,1
8923,GB1-2025,279,Wales,32,Ben Davies,Tottenham Hotspur,3,1
8924,GB1-2025,280,England,20,Tom Edozie,Wolverhampton Wanderers,3,1

### Fact
- f_events
- f_topscorers
- f_placements

### Dimensions
- d_countries
- d_matches
- d_teams
- d_titles
- d_squads

In [ ]:
# f_events
# f_topscorers
# f_placements

# d_countries
# d_matches
# d_teams
# d_titles
# d_squads

In [14]:
d_teams = pd.read_csv(r'..\data-csv\premier-logos.csv', sep=';')

display(d_teams)

                  team_name                                           svg_link
0           AFC Bournemouth  https://upload.wikimedia.org/wikipedia/en/e/e5...
1            AFC Sunderland  https://upload.wikimedia.org/wikipedia/sco/7/7...
2            Aston Villa FC  https://upload.wikimedia.org/wikipedia/en/9/9a...
3               Barnsley FC  https://upload.wikimedia.org/wikipedia/en/c/c9...
4           Birmingham City  https://upload.wikimedia.org/wikipedia/en/6/68...
5          Blackburn Rovers  https://upload.wikimedia.org/wikipedia/en/0/0f...
6              Blackpool FC  https://upload.wikimedia.org/wikipedia/en/d/df...
7          Bolton Wanderers  https://upload.wikimedia.org/wikipedia/en/8/82...
8         Bradford City AFC  https://upload.wikimedia.org/wikipedia/en/0/04...
9              Brentford FC  https://upload.wikimedia.org/wikipedia/en/2/2a...
10   Brighton & Hove Albion  https://upload.wikimedia.org/wikipedia/en/d/d0...
11             Cardiff City  https://upload.wikimedia.org/wikipedia/sco/3/3...
12        Charlton Athletic  https://upload.wikimedia.org/wikipedia/en/5/5b...
13               Chelsea FC  https://upload.wikimedia.org/wikipedia/en/c/cc...
14            Coventry City  https://upload.wikimedia.org/wikipedia/en/7/7b...
15        Crystal Palace FC  https://upload.wikimedia.org/wikipedia/en/a/a2...
16             Derby County  https://upload.wikimedia.org/wikipedia/en/4/4a...
17               FC Arsenal  https://upload.wikimedia.org/wikipedia/en/5/53...
18               FC Burnley  https://upload.wikimedia.org/wikipedia/en/6/6d...
19               FC Everton  https://upload.wikimedia.org/wikipedia/en/7/7c...
20                FC Fulham  https://upload.wikimedia.org/wikipedia/en/e/eb...
21             FC Liverpool  https://upload.wikimedia.org/wikipedia/en/0/0c...
22         FC Middlesbrough  https://upload.wikimedia.org/wikipedia/en/2/2c...
23            FC Portsmouth  https://upload.wikimedia.org/wikipedia/en/3/3c...
24               FC Reading  https://upload.wikimedia.org/wikipedia/en/1/11...
25           FC Southampton  https://upload.wikimedia.org/wikipedia/en/c/c9...
26               FC Watford  https://upload.wikimedia.org/wikipedia/en/e/e2...
27        Huddersfield Town  https://upload.wikimedia.org/wikipedia/en/4/43...
28                Hull City  https://upload.wikimedia.org/wikipedia/en/5/54...
29          Ipswich Town FC  https://upload.wikimedia.org/wikipedia/en/4/43...
30          Leeds United FC  https://upload.wikimedia.org/wikipedia/en/5/54...
31        Leicester City FC  https://upload.wikimedia.org/wikipedia/en/2/2d...
32               Luton Town  https://upload.wikimedia.org/wikipedia/en/9/9d...
33       Manchester City FC  https://upload.wikimedia.org/wikipedia/en/e/eb...
34     Manchester United FC  https://upload.wikimedia.org/wikipedia/en/7/7a...
35         Newcastle United  https://upload.wikimedia.org/wikipedia/en/5/56...
36             Norwich City  https://upload.wikimedia.org/wikipedia/en/1/17...
37        Nottingham Forest  https://upload.wikimedia.org/wikipedia/en/e/e5...
38          Oldham Athletic  https://upload.wikimedia.org/wikipedia/en/a/a2...
39      Queens Park Rangers  https://upload.wikimedia.org/wikipedia/en/3/31...
40         Sheffield United  https://upload.wikimedia.org/wikipedia/en/9/9c...
41      Sheffield Wednesday  https://upload.wikimedia.org/wikipedia/en/a/a5...
42               Stoke City  https://upload.wikimedia.org/wikipedia/en/b/bf...
43         Swansea City AFC  https://upload.wikimedia.org/wikipedia/sco/f/f...
44          Swindon Town FC  https://upload.wikimedia.org/wikipedia/en/a/a3...
45        Tottenham Hotspur  https://upload.wikimedia.org/wikipedia/en/b/b4...
46     West Bromwich Albion  https://upload.wikimedia.org/wikipedia/en/8/8b...
47          West Ham United  https://upload.wikimedia.org/wikipedia/en/c/c2...
48           Wigan Athletic  https://upload.wikimedia.org/wikipedia/en/4/43...
49    Wimbledon FC (- 2004)  https://upload.wikimedia.org/wikipedia/en/b/b3...
50  Wolverhampton Wanderers  https://upload.wikimedia.org/wikipedia/en/f/fc...

In [13]:
d_matches = pd.read_csv(r'..\data-csv\premier-matches.csv')

display(d_matches)

,season_id,round_id,match_id,home_team,final_score,away_team,date,referee,attendance
0,GB1-1992,R-1992-01,M-1992-01-001,Chelsea FC,1:1,Oldham Athletic,15/08/1992,Jim Borrett,20699
1,GB1-1992,R-1992-01,M-1992-01-002,Coventry City,2:1,Middlesbrough FC,15/08/1992,Howard King,12681
2,GB1-1992,R-1992-01,M-1992-01-003,Crystal Palace,3:3,Blackburn Rovers,15/08/1992,Roger Milford,17086
3,GB1-1992,R-1992-01,M-1992-01-004,Everton FC,1:1,Sheffield Wednesday,15/08/1992,Kelvin Morton,27687
4,GB1-1992,R-1992-01,M-1992-01-005,Ipswich Town,1:1,Aston Villa,15/08/1992,Alf Buksh,16818
...,...,...,...,...,...,...,...,...,...
13140,GB1-2025,R-2025-38,M-2025-38-006,Manchester City,1:2,Aston Villa,24/05/2026,Andrew Madley,60332
13141,GB1-2025,R-2025-38,M-2025-38-007,Nottingham Forest,1:1,AFC Bournemouth,24/05/2026,Craig Pawson,30741
13142,GB1-2025,R-2025-38,M-2025-38-008,Sunderland AFC,2:1,Chelsea FC,24/05/2026,Chris Kavanagh,47155
13143,GB1-2025,R-2025-38,M-2025-38-009,Tottenham Hotspur,1:0,Everton FC,24/05/2026,Michael Oliver,61812
13144,GB1-2025,R-2025-38,M-2025-38-010,West Ham United,3:0,Leeds United,24/05/2026,Anthony Taylor,62471